name: Build and Push Package
on:
    push:
        branches:
            - main
jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout tree
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Set-up OCaml
              uses: ocaml/setup-ocaml@v2
              with:
                  ocaml-compiler: "4.12"

            - id: version
              uses: codacy/git-version@2.7.1
              with:
                  release-branch: main

            - run: mkdir output
            - run: opam install . --deps-only
            - run: opam exec -- dune exec bin/lc.exe -- -version-str "${{ steps.version.outputs.version }}" -static-dir "./static" > output/thunderstore.toml
            - env:
                  THUNDERSTORE_TOKEN: ${{ secrets.THUNDERSTORE_TOKEN }}
              run: |
                  cd output
                  ../vendored/tcli publish --token $THUNDERSTORE_TOKEN

            - id: tag_version
              uses: mathieudutour/github-tag-action@v6.1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  custom_tag: v${{ steps.version.outputs.version }}
