name: Build and Push Package
on:
    push:
        branches:
            - main
jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout tree
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - id: version
              uses: codacy/git-version@2.7.1
              with:
                  release-branch: main

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: false
                  tags: "local"
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  build-args: |
                      TOKEN=${{ secrets.THUNDERSTORE_TOKEN }}
                      VERSION=${{ steps.version.outputs.version }}

            - run: docker run local

            - id: tag_version
              uses: mathieudutour/github-tag-action@v6.1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  custom_tag: v${{ steps.version.outputs.version }}
